### ISSUE TITLE
favoriting gif issue on smugboard

### ISSUE THREAD

**Issue by BatmanNova** [Rushnett/starboard#30]
When favoriting a .gif that was posted to smugboard the .gif does not display in your favorites when you have the proper .gif link favorited:
![image](https://user-images.githubusercontent.com/35268584/226962301-c782dd60-a5e5-49d8-bdcf-fc364fdcf041.png)

when you only have the smugboard .gif favorited, it does display but when clicked on the .gif link is "https://risu.dev":
https://gyazo.com/dedd7e8a2e020888b72c94bcb4b3907f

**Comment by naeruru** [comment]
Interesting. Apparently the favorite button that shows up in an embed does not redirect to the image url property of an embed, but rather redirects to the overall url property of the embed. However, the overall url needs to be exactly the same to merge multiple embeds into one so I can display multiple images at a time. This seems like an oversight on Discord's part. Doesn't really seem intuitive.

I just now tried to make the URLs with different queries (`?i=0`, `?i=1`), but it still wont merge the embed that way. That means I will likely have to just set the overall url to one of the images. Unfortunately that also means that if you favorite a gif that isn't the first gif, it will redirect to the first gif. But I guess that's better than redirecting to my site.

I will keep trying for other solutions, but it seems like I will have to go with the above.

**Comment by naeruru** [comment]
addressed in https://github.com/naexris/starboard/commit/33fac0cea6ee55ccc93a78acfdca146ad4b050c4. will continue to monitor for real fix.
