### ISSUE TITLE
QOL Query. 

### ISSUE THREAD

**Issue by Mazmol** [Rushnett/starboard#36]
Allow discord bot to listen to if reaction have been removed by another User 
and delete the post in the location it was posted.

For Example 

A) a person is posted and star 
a.1) goes on board

B) A person that has permissions to delete reactions from it  deletes it
b.1) bot remove the message from channel.

**Comment by naeruru** [comment]
This already works for bulk remove, but I didn't realize they added a feature to remove individual reacts.  I will fix that in next commit

**Comment by Mazmol** [comment]
Thank you ❤️


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
