### ISSUE TITLE
option to use a webhook for posting

### ISSUE THREAD

**Issue by Vendicated** [Rushnett/starboard#38]
First of all thanks a lot for the bot, been using it for a long time now and it has always worked well!!

Posting as normal embed has the limitation that the bot can't use external emojis

This could be solved by instead using a webhook, since webhooks can use any emoji across discord. An important detail is that the webhook needs to be created manually by a user, not a bot. But considering you already have to hardcode a channel id in config.json anyway, the config could just have a new field for webhook url which is preferred over the channel id

**Comment by naeruru** [comment]
Sure, I can add an option for using a webhook. but let me ask, why can't the webhook be created by the bot itself using discordjs's `channel.createWebhook()`? Is it simply because doing so does not have the benefits of being able to use any emoji across discord?

**Comment by Vendicated** [comment]
correct, webhooks created by bots cannot use custom emotes. likely done by discord to counteract bots like NotQuiteNitro? they have stated that this is intended behaviour so it's likely not getting changed https://github.com/discord/discord-api-docs/issues/5357#issuecomment-1230709699 

iirc, edits can however, just the initial message create can't. so instantly editing the message might be an option if you wanna go that route

well actually i last tested this ages ago so maybe they changed it by now? i highly doubt it but i would still double check before doing any workarounds (i can't rn sorry 😅)

**Comment by naeruru** [comment]
from what I tested, editing a bot created webhook wont show global emotes unfortunately, but a user created one will like you said. surprised I didnt know about this... it even works with emotes from twitch. I'll work on something this weekend hopefully!!

**Comment by naeruru** [comment]
pr is stable and working good, it's running in a high volume server right now. will merge it this weekend after I've fully confirmed it's good
