### ISSUE TITLE
[idea] Integrate Threads into Stars

### ISSUE THREAD

**Issue by Mazmol** [Rushnett/starboard#40]
Possible way to intergreate threads once star then you can link it to the channel. 

don't know if possible since threads get archived / deleted.

**Comment by naeruru** [comment]
could you explain more? I'm not entirely sure what you mean by integrating threads. do you mean an options for creating a thread for each embed?

**Comment by Mazmol** [comment]
no I mean - be able to star a message in a discord thread and it then goes to starboard. not sure if it will work cause discord threads will expire

**Comment by naeruru** [comment]
ah I see. well reacting to thread messages is already possible. here is an example of what it looks like in a thread called "ex thread":

![image](https://github.com/naeruru/starboard/assets/9059594/436f54d4-32ed-4664-9850-409bcc2df1f8)

**Comment by Mazmol** [comment]
ah - will that expire though? and if you jump to it will it re open it.

**Comment by naeruru** [comment]
Ah sorry I thought I replied. A bit late, but if the thread is stale or closed, it will still properly link to the message with the original message link and won't cause new activity just by clicking on it. however if the thread is deleted, it will not be able to properly link to it, just like a regular channel being deleted. so there should be no issues with -expiration-
